# This file was generated by the {rix} R package v0.17.4 on 2026-03-07
# with following call:
# >rix::rix(date = "2026-01-19",
#  > r_pkgs = all_r_pkgs,
#  > system_pkgs = system_pkgs,
#  > git_pkgs = NULL,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = FALSE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-19.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      arrow
      blastula
      cli
      copula
      covr
      crew
      DBI
      dbplyr
      desc
      devtools
      dplyr
      DT
      duckdb
      duckplyr
      dygraphs
      evd
      extRemes
      forecast
      gert
      ggplot2
      gh
      glue
      here
      httr2
      jsonlite
      knitr
      lubridate
      mev
      mgcv
      mirai
      pkgload
      plotly
      pointblank
      quantreg
      quarto
      ranger
      rix
      rlang
      rmarkdown
      scales
      shiny
      shinylive
      SpatialExtremes
      tarchetypes
      targets
      testthat
      tidyr
      usethis
      withr
      xts
      zoo;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      nix
      pandoc
      quarto
      R
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    # Override R_LIBS_SITE to prevent nested nix-shell contamination.
    # Without this, impure shells inherit R_LIBS_SITE from the outer shell,
    # mixing .so files from different nixpkgs revisions → ABI mismatch → segfault.
    # This computes the correct paths at Nix eval time from the transitive
    # closure of R package dependencies.
    shellHook = let
      allDeps = pkgs.lib.closePropagation rpkgs;
      rPkgDeps = builtins.filter (p: builtins.pathExists "${p}/library") allDeps;
    in ''
      export R_LIBS_SITE="${builtins.concatStringsSep ":" (map (p: "${p}/library") rPkgDeps)}"
    '';
  };
in
  {
    inherit pkgs shell;
  }
