# This file was generated by the {rix} R package v0.17.4 on 2026-03-07
# with following call:
# >rix::rix(date = "2026-01-19",
#  > r_pkgs = all_r_pkgs,
#  > system_pkgs = system_pkgs,
#  > git_pkgs = NULL,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = FALSE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-19.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      arrow
      blastula
      cli
      copula
      covr
      crew
      DBI
      dbplyr
      desc
      devtools
      dplyr
      DT
      duckdb
      duckplyr
      dygraphs
      evd
      extRemes
      forecast
      gert
      ggplot2
      gh
      glue
      here
      httr2
      jsonlite
      knitr
      lubridate
      mev
      mgcv
      mirai
      pkgload
      plotly
      pointblank
      quantreg
      quarto
      ranger
      rix
      rlang
      rmarkdown
      scales
      shiny
      shinylive
      SpatialExtremes
      tarchetypes
      targets
      testthat
      tidyr
      usethis
      withr
      xts
      zoo;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      nix
      pandoc
      quarto
      R
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    # Guard against nested nix-shell R_LIBS_SITE contamination.
    # In clean environments (CI, pure shells), R_LIBS_SITE has ~218 paths
    # from Nix setup hooks — leave it alone. In contaminated nested impure
    # shells, it has 500+ paths mixing .so files from different nixpkgs
    # revisions → ABI mismatch → segfault. Only override when contaminated.
    shellHook = let
      allDeps = pkgs.lib.closePropagation rpkgs;
      rPkgDeps = builtins.filter (p: builtins.pathExists "${p}/library") allDeps;
    in ''
      _n_paths=$(echo "$R_LIBS_SITE" | tr ':' '\n' | wc -l)
      if [ "$_n_paths" -gt 300 ]; then
        export R_LIBS_SITE="${builtins.concatStringsSep ":" (map (p: "${p}/library") rPkgDeps)}"
      fi
    '';
  };
in
  {
    inherit pkgs shell;
  }
